name: convert-ipynb-to-md-push-to-gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
    # branches: [ master ]
  # pull_request:
    # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: tj1997/jupyter-nb-images:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - name: Convert to markdown
        run: jupyter nbconvert --to markdown ./**/*.ipynb
          
      - name: Pull repo teejas.github.io and copy over files
        run: |
          git clone https://github.com/teejas/teejas.github.io.git
          cp ./**/*.md teejas.github.io/content/notebooks
          cp ./**/*_files teejas.github.io/content/notebooks
          
      
