# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env hadolint-install
      - name: Lint Dockerfiles
        run: make -C main hadolint-all
      - name: Run pre-commit hooks
        run: make -C main pre-commit-all
      - name: Build Docker Images
        run: make -C main build-test-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login --username
          '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master'
        run: make -C main push-all
